### ISSUE TITLE
Module installation fails

### ISSUE THREAD

**Issue by b263** [example42/puppet-php#109]
php::module { 'xdebug': }

leads to the following error:

    Warning: Scope(Php::Module[xdebug]): Could not look up qualified variable 'php::package'; class php has not been evaluated
    Error: Could not find dependency Package[undef] for Package[PhpModule_xdebug] at /etc/puppet/modules/php/manifests/module.pp:93

**Comment by alvagante** [comment]
You should 
include php class before using php::module
