### ISSUE TITLE
cannot set both source and template on node X

### ISSUE THREAD

**Issue by choonchernlim** [example42/puppet-php#75]
I had successful experience getting this module to work on Ubuntu, but I am having problem trying to get it to work on RHEL 6.

I tried to configure using the default: `class { 'php': }`

The error I'm getting is this:-
```
Error: PHP: cannot set both source () and template () on node X
Error: PHP: cannot set both source () and template () on node X
```

I read `init.pp` and the error seems to be happening on this:-
```
  if ($php::source and $php::template) {
    fail ("PHP: cannot set both source and template")
  }
```

When I inspected these values, both are empty strings. So I decided to comment out that check and set both `$manage_file_source` and `$manage_file_content` to `undef`, but then I get error about `$php::source_dir` being empty when trying to create `php.dir`.

This is getting very frustrating. It works flawlessly on Ubuntu, but I can't cannot replicate my success on RHEL. I'm running Puppet 3.7.3 on RHEL 6, by the way.
```
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Red Hat Enterprise Linux Server release 6.5 (Santiago)
``
Any idea why this is happening? Thank you.

**Comment by vitxd** [comment]
same problem here, I can't really get around it, even specifying either source or template.
I'm on Centos 7

**Comment by ddeboer** [comment]
> Core reason could be that on Puppet 4 / future parser (don't know since which version) an empt string evaluates as true, while before it was evaluated as false.

> Saying this without having tested that or having looked with care at the code

This is exactly right: Puppet 3.7 future/Puppet 4 interprets empty strings as `true`.

**Comment by ranjeetkgupta** [comment]
Hi folks . I have run into the same problem. "Error: PHP: cannot set both source () and template () on node X"

I am using future parser on PE 3.8. I cant switch off the future-parser as I am using 'collection.each{}' construct in a different manifest. Is there a work-around for this ? I am using centos 6.6

**Comment by diglin** [comment]
Just to confirm you that the `parser = future` make me trouble with the source and template condition on puppet 3.8. Removing it fix it. However I cannot use anymore the each feature of puppet future

**Comment by andrewhertog** [comment]
See pull request: https://github.com/example42/puppet-php/pull/96

**Comment by alvagante** [comment]
PR #96 merged issue should be fixed
