### ISSUE TITLE
php::augeas writes to php.ini before php package is installed

### ISSUE THREAD

**Issue by catalinpan** [example42/puppet-php#85]
Hi,

On the initial puppet run php::augeas writes the values on the php.ini before the php package installation. This results in the php.ini having only the php::augeas values.

As a "fix" I have added require => Package['php'] on the augeas.pp:

                     $changes = $ensure ? {
                               present => [ "set '${entry}' '${value}'" ],
                               absent  => [ "rm '${entry}'" ],
                               require => Package['php'],
                                           }

                     augeas { "php_ini-${name}":
                               incl    => $target,
                               lens    => 'Php.lns',
                               changes => $changes,
                               require => Package['php'],
                                          }

and now works as expected.

I am wondering, how can I change the behaviour without modifying the module or creating a wrapper class?

Thanks

**Comment by alvagante** [comment]
I consider this a bug, please send a PR with the fix you found

**Comment by catalinpan** [comment]
I have done the PR.
Thanks.
