### ISSUE TITLE
Error: Could not find dependent Service[nginx] for File[php.conf] at ..

### ISSUE THREAD

**Issue by leshiynyc** [example42/puppet-php#95]
Hi, 

I am trying to do something like this : 
 ``` 
class { 'php':  service => 'nginx'  }
php::pecl::module { 'mongo': } 
```
and keep getting the following error during catalog compilation :
`` Error: Could not find dependent Service[nginx] for File[php.conf] at .. ``

**Comment by alvagante** [comment]
If you specify service => 'nginx' the module expects that you have nginx installed and managed in some way , with a relevant service resource.

**Comment by leshiynyc** [comment]
@alvagante  thanks !
